Add nvidia information
SystemCrafters/wiki-site pull request #17
Opened 2021-06-10 21:43 UTC by minikN

Please proof read and feel free to add/edit/delete styling/whatever you want.

2021-06-14 00:24 UTC, TheCatster requested changes
Alright, you asked for editing, and I've given you almost as thorough a review as I can! Please don't take any of it as finding errors for the sake of it, just trying to help your article flow with the rest and be the best it can!

Many comments have been left; please consider them all!

2021-06-14 00:24 UTC, TheCatster commented on content/guix/nvidia.org
> +#+TITLE: Proprietary NVIDIA drivers
Make title fully capital, so =drivers= should be =Drivers=.

2021-06-14 00:24 UTC, TheCatster commented on content/guix/nvidia.org
> +GNU Guix makes installing and using the proprietary nvidia drivers more difficult than one may be used to coming from other distributions. However, it is possible and this page tries to provide guida
Capitalise NVIDIA. For =... page tries to provide...+, try instead just writing something along the lines of =...is explained here...=. It is assumed that this page will help with the aforementioned problem.

2021-06-14 00:24 UTC, TheCatster commented on content/guix/nvidia.org
> +** Using the channel
For legibility, consider adding a newline between all of your headings.

2021-06-14 00:24 UTC, TheCatster commented on content/guix/nvidia.org
> +  If using the ~nonguix~ channel, the ~nvidia-driver~ package, contains the proprietary drivers for GNU Guix. If you followed the [[/guix/nonguix-installation-guide][nonguix installation guide]] this
> ~nvidia-driver~ package,

Remove that comma. Instead, after referencing the installation guide link, put a comma there:

> If you followed the [[/guix/nonguix-installation-guide][nonguix installation guide]],

Just gives that more natural pause.

2021-06-14 00:24 UTC, TheCatster commented on content/guix/nvidia.org
> +  #+END_SRC
I'm not sure it's worth reiterating nonguix here (at least how to add it). I would safely assume that, since you've linked the guide, if they do not have nonguix, they do not want it. Maybe reinforce it above and say, if you do want it, check it out over there (of course more formally articulated than that).

2021-06-14 00:24 UTC, TheCatster commented on content/guix/nvidia.org
> +   Your system configuration is usually located at ~/etc/config.scm~. We need to add several lines of code to make your system load the drivers properly. Open the file to edit it and make sure you ha
> Open the file to edit it, and make sure you have write permissions.

Adds a more natural pause.

2021-06-14 00:24 UTC, TheCatster commented on content/guix/nvidia.org
> +   In order to have ~libglx~ working. The ~nvidia-driver~ package needs to be grafted instead of ~mesa~. It needs to be renamed to have the same number of characters as ~mesa~. More information can b
>  In order to have ~libglx~ working, the ~nvidia-driver~ package needs to be grafted instead of ~mesa~.

I think you meant that instead.

2021-06-14 00:24 UTC, TheCatster commented on content/guix/nvidia.org
> +*** Operating System configuration
Looks a bit awkward with two capitalised words and then one not. Consider writing =OS configuration=.

2021-06-14 00:24 UTC, TheCatster commented on content/guix/nvidia.org
> +   From here on everything metioned should be placed in your ~operating-system~ block:
> From here on, everything mentioned should be placed in your ~operating-system~ block:

Added comma and fixed typo.

2021-06-14 00:24 UTC, TheCatster commented on content/guix/nvidia.org
> +   #+begin_src scheme
Would add spacing between source blocks, same as headings.

2021-06-14 00:24 UTC, TheCatster commented on content/guix/nvidia.org
> +   The system configuration is now complete. However, you probably want to setup a login manager, right? No matter hat login manager you use, you need to list the nvidia-driver in the ~xorg-configura
> No matter what login manager you use,

2021-06-14 00:24 UTC, TheCatster commented on content/guix/nvidia.org
> +   You can find examples for addition configuration in [[https://github.com/daviwil/dotfiles/blob/master/Systems.org][David's]] and [[https://github.com/minikN/guix/blob/main/base-system.scm#L37-L103
> additional configurations

Also, instead of saying "my," which is sort of vague in a community wiki, feel free to say "minikN's"!

2021-06-14 00:24 UTC, TheCatster commented on content/guix/nvidia.org
> +   However, the actual value of the option is dependent on your monitor setup. I explained this on the [[https://github.com/ch11ng/exwm/wiki#issues-with-screen-tearing][EXWM Wiki]] in greater detail.
> This was explained

Since the majority of the text is in third/second person, try not to use personal pronouns. Instead, rearrange the sentence, or include your name! This has occurred before, so be on the lookout for it throughout the text.

2021-06-14 00:24 UTC, TheCatster commented on content/guix/nvidia.org
> +   For me, enable a full composition pipeline has always worked. However on GNU Guix it didn't for some reason. Maybe it'll work for you? In any case, another way is to use a compositor like [[https:
Same as above.

2021-06-14 23:02 UTC, TheCatster commented
Looks great to me! Merging now.

2021-06-14 23:03 UTC, merged

2021-06-15 12:12 UTC, minikN commented
Thanks for merging, but reading through it again, there's still some stuff that needs ironing out. Sorry I didn't catch it earlier. Especially this

> That’s about it. The last thing you need to do is to reconfigure the system so your changes get applied. You need sudo in order to do that. You can use the following command making sure you replace <user> with your own user name:

The last sentence is obsolete because the command following it changed.

> Forcing a full composition pipeline can help to avoid screen tearing. You can consult the Arch Wiki if you want to know about it. To put it simple, you need to add the MetaModes option to your ~Section “Screen”~ block of your xorg configuration. Like this:

`Section “Screen”` is not formatted properly.

> Generally, enabling the full composition pipeline works to get rid of screen tearing. However on GNU Guix it didn’t for some reason. Maybe it’ll work for you? In any case, another way is to use a compositor like picom (formely known as compton). Now, there are multiple ways to set up a compositor. Personally, I want to use Emacs, more specifially EXWM as my window manager. Again, probably about a dozen ways of getting it to work. However, there is an emacs-exwm package. I wanted to use it. Unfortunately, I was not able to enable picom using this package. In addition, it still runs on Emacs 27.2, I’d rather use version 28 with native compilation. So I wrote my own package definition inheriting from emacs-exwm which automatically starts picom and uses the native-compilation branch.

I use `I`, `me`, `personally` and whatnot here. Should rephrase this part to be in line with your feedback.

Sorry I'm pretty busy with work atm and didn't pay as much attention to it as I should have.

2021-06-15 13:00 UTC, daviwil commented
Thanks so much for taking the time to contribute this, @minikN!  It's really going to help a lot of people out ✨

2021-06-15 13:40 UTC, minikN commented
> Thanks so much for taking the time to contribute this, @minikN! It's really going to help a lot of people out ✨

You're welcome. Looking forward to contribute more if I can. The time you put into this is worth so much more. Without you, I wouldn't know a thing about Guix. That alone justifies my contribution. Thanks.