adding information about set up for ZNC
SystemCrafters/wiki-site pull request #19
Opened 2021-06-13 17:25 UTC by nackjicholson

Hello, please read and consider this addition for merge.

Please tell me if I got the linking incorrect from the chat with us page to the ZNC setup page. I had some trouble figuring out how to properly build the wiki site locally for myself.

2021-06-13 18:38 UTC, TheCatster commented
I should have better documented the procedure, however the local build script and Emacs is all you should need. I can take a look in a little while.

2021-06-13 20:44 UTC, shombando reviewed
Great article, thanks. Just a couple suggestions.

2021-06-13 20:44 UTC, shombando commented on content/community/znc-bouncer-servers.org
> +#+begin_src
If you add `#+begin_src sh` then it will more reliably do correct syntax highlighting. Not necessary but if you want to your could specify the language for each code block.

2021-06-13 20:44 UTC, shombando commented on content/community/znc-bouncer-servers.org
> +Add this to cron by running =crontab -e=. This will attempt renewal everyday at 3:15 AM, you can change this time to any time you like.
I think commands should be enclosed by `~` so it would be `~crontab -e~`

2021-06-13 22:27 UTC, nackjicholson commented on content/community/znc-bouncer-servers.org
> +The following commands and configuration instructions will set up a secure ZNC server for personal use. You will need a CentOS 7 server or virtual machine, as well as a registered domain name. In the
s/runn/run

2021-06-13 22:30 UTC, nackjicholson commented on content/community/znc-bouncer-servers.org
> +You should now be to visit znc.example.com:6697 to use the ZNC web frontend. You can also connect to ZNC using =erc-tls=. If your browser blocks the 6697 port, read up on configuring settings to work
be -> be able

2021-06-14 03:38 UTC, nackjicholson commented on content/community/znc-bouncer-servers.org
> +Add this to cron by running =crontab -e=. This will attempt renewal everyday at 3:15 AM, you can change this time to any time you like.
Hey shom, what is the meaning difference between `=` and `~` in org-mode? They usually render out the same so I've never learned which one to use where.

2021-06-16 12:06 UTC, TheCatster requested changes

2021-06-16 12:06 UTC, TheCatster commented on content/community/znc-bouncer-servers.org
> +** Stuck on Alt. Name, switch back to main Nick
Just my two cents, but way too long of a heading. Try condensing it to something like “Fixing your nick.”

2021-06-16 12:06 UTC, TheCatster commented on content/community/znc-bouncer-servers.org
> +Occassionally, the ZNC server may log you in as your alt. name. Usually that will mean that your name will have a trailing =_= on it. If you get stuck like that and it's not because your main nick is
One “s” in occasionally, and don’t write “alt. name.” It seems like the sentence ends twice. Either formally write “alternate” every time or just “alt name.”

2021-06-16 12:06 UTC, TheCatster commented on content/community/znc-bouncer-servers.org
> +Occassionally, the ZNC server may log you in as your alt. name. Usually that will mean that your name will have a trailing =_= on it. If you get stuck like that and it's not because your main nick is
I’m on a phone so that’s all I see, but please fly check the grammar and see what else you can find error wise. Thanks!

2021-06-18 18:52 UTC, nackjicholson commented
@TheCatster @shombando Addressed those small problems. Thanks for the corrections and suggestions.

2021-06-23 12:21 UTC, shombando commented on content/community/znc-bouncer-servers.org
> +Add this to cron by running =crontab -e=. This will attempt renewal everyday at 3:15 AM, you can change this time to any time you like.
@nackjicholson ~  is for inline code and = is for verbatim. Themes and parsers take different liberties on how it's rendered. But I always use ~ for code/command snippets and = for file names/paths.
(Sorry for late reply)

2021-06-23 12:22 UTC, shombando approved these changes
Everything looks good, adding an approve but @daviwil or @TheCatster will need to merge.

2021-06-23 13:39 UTC, daviwil approved these changes
This is excellent, thanks so much for putting it together!

2021-06-23 13:40 UTC, merged